server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
spring:
  profiles:
    active: prod
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000  # 向连接池获取连接超过30秒就放弃
      minimum-idle: 5            # 最小连接数 注:作者推荐最小连接数和最大连接数都设置为10.
      maximum-pool-size: 20      # 最大连接数 4建议核服务器设置为10,8核服务器设置为20
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: DataSourceHikariCP   # 数据源名字
      connection-test-query: SELECT 1 # 连接成功的检查语句
      auto-commit: true
  servlet:
    multipart:
      max-file-size: 200KB
      max-request-size: 500KB
mybatis:
  type-aliases-package: com.lhjl.pojo  # 指定pojo类所在包路径
  mapper-locations: classpath:mapper/*.xml # 指定mapper映射文件
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
